[pytest]
markers =
    ui: pruebas automatizadas de interfaz con Selenium
    api: pruebas automatizadas de API con Requests
    smoke: pruebas principales de validación rápida
    e2e: pruebas de flujo completo end to end